server:
  port: 8888

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
          #Route 1 : redirige les requêtes /api/customers/** vers le microservice client
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            Path=/api/customers/**

          #Route 2 : redirige les requêtes /api/products/** vers le microservice produit
        - id: product-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            Path=/api/products/**
